name: ui
#  The toolstack used to build the application.
type: nodejs:10
build:
  flavor: default
# The configuration of app when it is exposed to the web.
web:
  locations:
    "/":
      root: "dist/angular-platformsh"
      index:
        - "index.html"
      headers:
        X-Frame-Options: SAMEORIGIN
      expires: 300
      scripts: true
      allow: false
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg|map)$:
          allow: true
        ^/robots\.txt$:
          allow: true
      passthru: /index.html
disk: 2048
# The hooks that will be performed when the package is deployed..
hooks:
  build: |
    set -e
    npm run build

